version: 2.1

_defaults: &defaults
  machine:
    docker_layer_caching: false
  working_directory: ~/repo
  environment:
    TERM: dumb

workflows:
  version: 2
  development:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/
    - integration:
        filters:
          tags:
            only: /^v.*/
    - publish-snapshot:
        context: nexus
        requires:
          - build
          - integration
        filters:
          branches:
            only:
              - master
    - publish:
        context: nexus
        requires:
          - build
          - integration
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Compile
        command: cat /dev/null | sbt -mem 7500 +validate

    - save_cache:
        paths:
        - ~/.ivy2/cache
        - ~/.m2
        - ~/.sbt
        - target
        key: v1-dependencies-{{ checksum "build.sbt" }}

  integration:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: docker info
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run:
          name: Start Docker Compose environment
          command: cat /dev/null | sbt dockerComposeUp
      - run:
          command: docker ps -a
      - run:
          name: yawn...
          command: sleep 5
      - run:
          name: Run integration test suite
          command: cat /dev/null | sbt -mem 4000 it:test
      - run:
          name: Stop Docker Compose environment
          command: cat /dev/null | sbt dockerComposeStop
  publish:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release snapshot version
        command: cat /dev/null | sbt -mem 7000 ci-release


  publish-snapshot:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release tagged version
        command: cat /dev/null | sbt -mem 7000 ci-release
